name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - run: docker compose build
      - run: docker tag johan-predicator johantran456/johan-predicator
      - run: docker login -u johantran456 -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push johantran456/johan-predicator      
      - run: sshpass -p Monsupermotdepasse!42 ssh ubuntu@20.86.55.5 "docker compose pull johantran456/johan-predicator"
